//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.1
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserTreeLib {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StrRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StrRes() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UserTreeLib.StrRes", typeof(StrRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   User Infomation Downloading に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgDownload {
            get {
                return ResourceManager.GetString("MsgDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No User に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgNoData {
            get {
                return ResourceManager.GetString("MsgNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All Users に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TreeRoot {
            get {
                return ResourceManager.GetString("TreeRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unidentified User に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnidentifiedUserCode {
            get {
                return ResourceManager.GetString("UnidentifiedUserCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}(Unknown) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnknownUserDisplayName {
            get {
                return ResourceManager.GetString("UnknownUserDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Account に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string USAccount {
            get {
                return ResourceManager.GetString("USAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Domain に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string USDomain {
            get {
                return ResourceManager.GetString("USDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}({1}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserDisplayName {
            get {
                return ResourceManager.GetString("UserDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string USID {
            get {
                return ResourceManager.GetString("USID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log Group に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string USLogGroup {
            get {
                return ResourceManager.GetString("USLogGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string USName {
            get {
                return ResourceManager.GetString("USName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PC に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string USPC {
            get {
                return ResourceManager.GetString("USPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string USSearch {
            get {
                return ResourceManager.GetString("USSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Security Group に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string USSecGroup {
            get {
                return ResourceManager.GetString("USSecGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select a user. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewerEmptyUserName {
            get {
                return ResourceManager.GetString("ViewerEmptyUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}({1} users) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewerGroupName {
            get {
                return ResourceManager.GetString("ViewerGroupName", resourceCulture);
            }
        }
    }
}
